### ISSUE TITLE
Would you please add combat extended support?

### ISSUE THREAD

**Issue by jinlan** [Mehni/PickUpAndHaul#21]
Currently, pawn does not check "bulk" when hauling. So a pawn with max bulk of 35 can easily haul 200 bulk of goods.

----------------------------------------------------------------------------------

Checked the source code. CE related code is commented out.

**Comment by Mehni** [comment]
Commented out for a reason.

I'll revisit in a week or two, once things have calmed down on the CE front. The current implementation of PU&H makes perfect CE support difficult.

I cannot guarantee full compatibility. Since so few mods actually add bulk, most of PU&H's functionality would be moot. We'll see.

**Comment by Trevinlc1997** [comment]
Mehni I am not sure if you are aware but Combat Extended Fast Tracks is merging into Combat Extended so you may have better luck.

It would be awesome if you could figure it out because my pawns can finally be walking pack animals lol.

**Comment by Mehni** [comment]
Was not aware, thanks for the pointer. As they're not up to speed with 1.1 yet, it'll remain as-is for now.

**Comment by Trevinlc1997** [comment]
@Mehni Hey just wanted to let you know that (if you haven't already heard) that combat extended 1.1 was released yesterday so maybe you could look into this on your free time.

**Comment by Mehni** [comment]
It's back.
