### ISSUE TITLE
Infinite loop, pick up and drop stuff.

### ISSUE THREAD

**Issue by zozilin** [Mehni/PickUpAndHaul#23]
I am not sure if it is this mod problem, but it does happen when a pawn tries to pick something up. They'll just pick up and drop a thing several times a second. 
Drafting doesn't help, the game starts giving "10 jobs in 10 ticks" error.
This happened before, but everytime I had to down a pawn to stop it.
I've attached logs both for loop and drafted error.
[Infinite loop.txt](https://github.com/Mehni/PickUpAndHaul/files/2932419/Infinite.loop.txt)
[When drafted.txt](https://github.com/Mehni/PickUpAndHaul/files/2932421/When.drafted.txt)

**Comment by zozilin** [comment]
I just found that it may be somehow related to Psychology mod, a Panic attack when suffering from Anxiety. I will try asking there too.

**Comment by Mehni** [comment]
More likely to be caused by some other mod, yes. Psychology is mentioned in the log so that is probable. Especially when drafted, Pick up and Haul doesn't interfere with that.

If you have a savefile with just the bare minimum of mods to repro the issue, I can determine if Pick up and Haul is misbehaving. Otherwise I'm inclined to believe your issue is not related to Pick up and Haul.

**Comment by zozilin** [comment]
Yeah, I think so too. I'll try testing it after Psychology author looks into it. And I am pretty sure now, it's not this mod's issue.

**Comment by Mehni** [comment]
I always appreciate hearing it.

Any feedback from Psychology? If so, this issue can be closed.

**Comment by zozilin** [comment]
They've got my report and will look into it. Nothing yet. 
Yes, I think it should be closed here.
