### ISSUE TITLE
Doesn't work for building

### ISSUE THREAD

**Issue by crazyjat** [Mehni/PickUpAndHaul#53]
I have this mod installed and enabled and it works great for transferring materials, but does not work at all for building. For example, I'm trying to build a new Wind Turbine and my builder goes and picks up one building material at a time and hauls it to the building site. One stack of components, one stack of steel, etc. Why does this mod not work with constructing a building?

**Comment by Mehni** [comment]
Simply put: because that's not in scope of this mod. The behaviour you describe is not an intended feature, and won't ever be. You'll find the same behaviour when loading up caravans or pod launchers.

Construction is a completely different job from hauling. If you want the thing you mention, put down a high priority stockpile near the blueprint.

There are both technical and gameplay related reasons as to why, but it basically boils down to "too much effort". It's deliberately not a feature.
